# Generated by Django 2.2.6 on 2019-10-16 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bala',
            fields=[
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Preço')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Quantidade não pode ser menor que 0')], verbose_name='Quantidade')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
            ],
        ),
    ]
