# Generated by Django 2.2.6 on 2019-10-16 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bala',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bala',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Preço não pode ser negativo')], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='bala',
            name='tipo',
            field=models.BooleanField(verbose_name='Bala para diabéticos'),
        ),
    ]
