# Generated by Django 2.2.6 on 2019-10-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balas', '0002_auto_20191016_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bala',
            options={'verbose_name': 'Bala', 'verbose_name_plural': 'Balas'},
        ),
    ]
