# Generated by Django 2.2.6 on 2019-10-23 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Saldo não pode ser negativo')], verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
            },
        ),
    ]
